// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdvhkwaclexttpqzodxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkdmhrd2FjbGV4dHRwcXpvZHhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxMDczNTIsImV4cCI6MjA1NTY4MzM1Mn0.1HFSexTLHe6ZsrNBBaYhV9VxoOBLd5vov8DnrUpf5iQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);